catalog/api/urls.py
from django.urls import include, path
from rest_framework import routers

from .views import ElementRBookViewSet, ElementViewSet, RBookViewSet

app_name = "api"

router_v1 = routers.DefaultRouter()

router_v1.register("reference_book", RBookViewSet)
router_v1.register("element", ElementViewSet)
router_v1.register(
    r"reference_book/((?P<reference_book_id>[^/.]+))/element",
    ElementRBookViewSet,
    basename="elements",
)

urlpatterns = [
    path("v1/", include(router_v1.urls)),
]

catalog/catalog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Cервис терминологии API",
        default_version="v1",
        description="Документация для приложения Cервис терминологии",
        # terms_of_service="URL страницы с пользовательским соглашением",
        contact=openapi.Contact(email="admin@fake.fake"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("", include("reference_book.urls", namespace="reference_book")),
    path("admin/", admin.site.urls),
    path("about/", include("about.urls", namespace="about")),
    path("api/", include("api.urls")),
]

urlpatterns += [
   url(r'^swagger(?P<format>\.json|\.yaml)$',
       schema_view.without_ui(cache_timeout=0), name='schema-json'),
   url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0),
       name='schema-swagger-ui'),
   url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0),
       name='schema-redoc'),
]

catalog/reference_book/urls.py
from django.urls import path

from . import views

app_name = "reference_book"

urlpatterns = [
    path(
        "",
        views.index,
        name="index",
    ),
    path(
        "reference_book/<int:reference_book_id>/",
        views.reference_book_detail,
        name="reference_book_detail",
    ),
    path(
        "create_reference/",
        views.reference_book_create,
        name="reference_book_create",
    ),
    path(
        "element/<int:element_id>/",
        views.element_detail,
        name="element_detail",
    ),
    path(
        "reference_book/<int:reference_book_id>/edit/",
        views.reference_book_edit,
        name="reference_book_edit",
    ),
    path(
        "element/<int:element_id>/edit/",
        views.element_edit,
        name="element_edit",
    ),
    path(
        "create_element/",
        views.element_create,
        name="element_create",
    ),
]

catalog/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {% now "Y" %} Copyright <span style="color:black">"Cервис терминологии"</span>
  </p>
</footer>

catalog/templates/includes/header.html
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'reference_book:index' %}">
        {% load static %}
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:black">"Cервис терминологии"</span>
      </a>

      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.view_name  == 'reference_book:index' %} 
            active
          {% endif %}" href="{% url 'reference_book:index' %}">
            Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.view_name  == 'reference_book:reference_book_create' %} 
            active
          {% endif %}" href="{% url 'reference_book:reference_book_create' %}">
            Добавить справочник</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.view_name  == 'reference_book:element_create' %} 
            active
          {% endif %}" href="{% url 'reference_book:element_create' %}">
            Добавить элемент</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.view_name  == 'about:author' %} 
            active
          {% endif %}" href="{% url 'about:author' %}">
            Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.view_name  == 'about:tech' %} 
          active
        {% endif %}" href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="">
            Пользователь: {{ user.username }}
          </a>
        <li>
          {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">
            Войти
          </a>
        </li>

        {% endif %}
      </ul>
    </div>
  </nav>
</header>

catalog/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
        Предыдущая
      </a>
    </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}</span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">
        Следующая
      </a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
        Последняя
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}