catalog/api/urls.py
from django.urls import include, path
from rest_framework import routers

from .views import ElementRBookViewSet, ElementViewSet, RBookViewSet

app_name = "api"

router_v1 = routers.DefaultRouter()

router_v1.register("reference_book", RBookViewSet)
router_v1.register("element", ElementViewSet)
router_v1.register(
    r"reference_book/((?P<reference_book_id>[^/.]+))/element",
    ElementRBookViewSet,
    basename="elements",
)

urlpatterns = [
    path("v1/", include(router_v1.urls)),
]

catalog/catalog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Cервис терминологии API",
        default_version="v1",
        description="Документация для приложения Cервис терминологии",
        # terms_of_service="URL страницы с пользовательским соглашением",
        contact=openapi.Contact(email="admin@fake.fake"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("", include("reference_book.urls", namespace="reference_book")),
    path("admin/", admin.site.urls),
    path("about/", include("about.urls", namespace="about")),
    path("api/", include("api.urls")),
]

urlpatterns += [
   url(r'^swagger(?P<format>\.json|\.yaml)$',
       schema_view.without_ui(cache_timeout=0), name='schema-json'),
   url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0),
       name='schema-swagger-ui'),
   url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0),
       name='schema-redoc'),
]

catalog/reference_book/urls.py
from django.urls import path

from . import views

app_name = "reference_book"

urlpatterns = [
    path(
        "",
        views.index,
        name="index",
    ),
    path(
        "reference_book/<int:reference_book_id>/",
        views.reference_book_detail,
        name="reference_book_detail",
    ),
    path(
        "create_reference/",
        views.reference_book_create,
        name="reference_book_create",
    ),
    path(
        "element/<int:element_id>/",
        views.element_detail,
        name="element_detail",
    ),
    path(
        "reference_book/<int:reference_book_id>/edit/",
        views.reference_book_edit,
        name="reference_book_edit",
    ),
    path(
        "element/<int:element_id>/edit/",
        views.element_edit,
        name="element_edit",
    ),
    path(
        "create_element/",
        views.element_create,
        name="element_create",
    ),
]

catalog/reference_book/models.py
from django.db import models


class RBook(models.Model):
    name = models.CharField(
        max_length=200,
        verbose_name="наименование",
    )
    short_name = models.CharField(
        max_length=10,
        verbose_name="короткое наименование",
    )
    description = models.TextField(
        verbose_name="описание",
    )
    ver = models.CharField(
        max_length=200,
        verbose_name="версия",
    )
    date_begin = models.DateField(
        verbose_name="дата начала действия справочника",
    )

    class Meta:
        verbose_name = "Справочник"
        verbose_name_plural = "Справочники"
        unique_together = (
            "name",
            "ver",
        )

    def __str__(self):
        return self.name


class Element(models.Model):
    parent_id = models.ForeignKey(
        RBook,
        on_delete=models.SET_NULL,
        null=True,
        related_name="elements",
        verbose_name="родительский идентификатор",
    )
    code = models.CharField(
        blank=False,
        max_length=200,
        verbose_name="код элемента",
    )
    val = models.CharField(
        blank=False,
        max_length=200,
        verbose_name="значение элемента",
    )

    class Meta:
        verbose_name = "Элемент справочника"
        verbose_name_plural = "Элементы справочника"

    def __str__(self):
        return self.code

catalog/reference_book/forms.py
from django import forms

from .models import RBook, Element


class RBookForm(forms.ModelForm):
    class Meta:
        model = RBook
        fields = (
            "name",
            "short_name",
            "description",
            "ver",
            "date_begin",
        )
        labels = {
            "name": "наименование",
            "short_name": "короткое наименование",
            "description": "описание",
            "ver": "версия",
            "date_begin": "дата начала действия справочника",
        }
        help_texts = {
            "name": "Введите наименование",
            "short_name": "Введите короткое наименование",
            "ver": "Укажите версию",
            "date_begin": "Введите дату начала действия справочника",
            "description": "Введите описание",
        }
        verbose_name = "Форма справочника"


class ElementForm(forms.ModelForm):
    class Meta:
        model = Element
        fields = (
            "parent_id",
            "code",
            "val",
        )
        labels = {
            "parent_id": "родительский идентификатор",
            "code": "код элемента",
            "val": "значение элемента",
        }
        help_texts = {
            "parent_id": "Введите сообщение",
            "code": "Введите код элемента",
            "val": "Введите значение элемента",
        }
        verbose_name = "Форма элемента'"

catalog/reference_book/views.py
from django.conf import settings
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import ElementForm, RBookForm
from .models import Element, RBook


def index(request):
    reference_book = RBook.objects.all()
    paginator = Paginator(reference_book, settings.POSTS_FOR_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "page_obj": page_obj,
    }
    return render(request, "reference_book/index.html", context)


def reference_book_detail(request, reference_book_id):
    reference_book = get_object_or_404(RBook, id=reference_book_id)
    elements = reference_book.elements.all()
    paginator = Paginator(elements, settings.POSTS_FOR_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    form = RBookForm()
    context = {
        "reference_book": reference_book,
        "page_obj": page_obj,
        "form": form,
    }
    return render(request, "reference_book/reference_book_detail.html", context)


def reference_book_create(request):
    form = RBookForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("reference_book:index")
    return render(request, "reference_book/create_reference_book.html", {"form": form})


def element_detail(request, element_id):
    element = get_object_or_404(Element, id=element_id)
    form = ElementForm()
    context = {
        "element": element,
        "form": form,
    }
    return render(request, "reference_book/element_detail.html", context)


def reference_book_edit(request, reference_book_id):
    reference_book = get_object_or_404(RBook, id=reference_book_id)

    form = RBookForm(request.POST or None, instance=reference_book)
    if form.is_valid():
        form.save()
        return redirect("reference_book:reference_book_detail", reference_book_id)
    context = {"form": form, "reference_book": reference_book, "is_edit": True}
    return render(request, "reference_book/create_reference_book.html", context)


def element_create(request):
    form = ElementForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("reference_book:index")
    return render(request, "reference_book/create_element.html", {"form": form})


def element_edit(request, element_id):
    element = get_object_or_404(Element, id=element_id)

    form = ElementForm(request.POST or None, instance=element)
    if form.is_valid():
        form.save()
        return redirect("reference_book:element_detail", element_id)
    context = {"form": form, "element": element, "is_edit": True}
    return render(request, "reference_book/create_element.html", context)

catalog/templates/reference_book/create_element.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить справочник
  {% endif %}
{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="card">
      <div class="card-header">
      {% if is_edit %}
        Редактировать запись
      {% else %}
        Добавить справочник
      {% endif %}
      </div>
      <div class="card-body">
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
        {% endfor %}
        {% endif %}

        <form method="post" enctype="multipart/form-data"
                {% if is_edit %}
                 action = "{% url 'reference_book:element_edit' element.id %}"
                {% else %}
                 action = "{% url 'reference_book:element_create' %}"
                {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
          <div class="form-group row my-3" {% if field.field.required %} aria-required="true" {% else %}
            aria-required="false" {% endif %}>
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}
              <span class="required text-danger">*</span>
              {% endif %}
            </label>
            <div>
              {{ field }}

              {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                {{ field.help_text|safe }}
              </small>
              {% endif %}
            </div>
          </div>
          {% endfor %}
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
              Сохранить
              {% else %}
              Добавить
              {% endif %}
            </button>
        </form>
      </div> 
    </div> 
</div> 


{% endblock %}

catalog/templates/reference_book/create_reference_book.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить справочник
  {% endif %}
{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="card">
      <div class="card-header">
      {% if is_edit %}
        Редактировать запись
      {% else %}
        Добавить справочник
      {% endif %}
      </div>
      <div class="card-body">
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
        {% endfor %}
        {% endif %}

        <form method="post" enctype="multipart/form-data"
                {% if is_edit %}
                 action = "{% url 'reference_book:reference_book_edit' reference_book.id %}"
                {% else %}
                 action = "{% url 'reference_book:reference_book_create' %}"
                {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
          <div class="form-group row my-3" {% if field.field.required %} aria-required="true" {% else %}
            aria-required="false" {% endif %}>
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}
              <span class="required text-danger">*</span>
              {% endif %}
            </label>
            <div>
              {{ field }}

              {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                {{ field.help_text|safe }}
              </small>
              {% endif %}
            </div>
          </div>
          {% endfor %}
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
              Сохранить
              {% else %}
              Добавить
              {% endif %}
            </button>
        </form>
      </div> 
    </div> 
</div> 


{% endblock %}

catalog/templates/reference_book/element_detail.html
{% extends 'base.html' %}

{% block title %}
Справочник {{ reference_book.name }}
{% endblock %}

{% block content %}
<div class="container py-5">
  <div class="row">
    <article class="col-12 col-md-9">
      <p>
        родительский идентификатор : {{ element.parent_id }} <br>
        код элемента : {{ element.code }} <br>
        значение элемента : {{ element.val }} <br>
      </p>
      <a class="btn btn-primary"  href="{% url 'reference_book:element_edit' element.id %}">редактировать запись</a>


    </article>
  </div>
</div>

{% endblock %}

catalog/templates/reference_book/index.html
{% extends 'base.html' %}

{% block title %}
Последние обновления на сайте
{% endblock %}

{% block content %}
<div class="container py-5">

    {% for reference_book in page_obj %}
    <p> Наименование справочника: {{ reference_book.name}} </p>
    <a href="{% url 'reference_book:reference_book_detail' reference_book.id %}">Подробная информация</a> <br>

    {% if not forloop.last %}
    <hr>
    {% endif %}
    {% endfor %}
  {% include 'includes/paginator.html' %}
</div>
{% endblock %}

catalog/templates/reference_book/reference_book_detail.html
{% extends 'base.html' %}

{% block title %}
Справочник {{ reference_book.name }}
{% endblock %}

{% block content %}
<div class="container py-5">
  <div class="row">
    <article class="col-12 col-md-9">
      <p>
        идентификатор справочника : {{ reference_book.id }} <br>
        наименование : {{ reference_book.name }} <br>
        короткое наименование : {{ reference_book.short_name }} <br>
        описание : {{ reference_book.description }} <br>
        версия : {{ reference_book.ver }} <br>
        дата начала действия справочника : {{ reference_book.date_begin }} <br>
        <a class="btn btn-primary"  href="{% url 'reference_book:reference_book_edit' reference_book.id %}">редактировать запись</a>
        <br>
        Элементы справочника:
      </p>
    <hr>

    {% for element in page_obj %}
    <div class="media mb-4">
      <div class="media-body">
          <p>
            Код элемента : {{ element.code }} <br>
            Значение элемента : {{ element.val }} <br>
            <a href="{% url 'reference_book:element_detail' element.id %}">Подробная информация</a> <br>
            {% if not forloop.last %}
            <hr>
            {% endif %}
          </p>
        </div>
      </div>
  {% endfor %}

    </article>
  </div>
  {% include 'includes/paginator.html' %}
</div>

{% endblock %}